---
modules-search: [ local ]

instances:
    - id: initialize_pacman
      module: shellprocess
      config: shellprocess_initialize_pacman.conf
    - id: xivastudio
      module: netinstall
      config: netinstall-xivastudio.conf

sequence:
    - show:
          - welcome
          - locale
          - keyboard
          - partition
          - netinstall@xivastudio
          - users
          - summary
    - exec:
          - partition
          - luks-pbkdf
          - mount
          - unpackfs
          - networkcfg
          - machineid
          - fstab
          - locale
          - keyboard
          - shellprocess@initialize_pacman
          - packages
          - localecfg
          - luksopenswaphookcfg
          - luksbootkeyfile
          - initcpiocfg
          - initcpio
          - users
          - displaymanager
          - mhwdcfg
          - hwclock
          - services
          - grubcfg
          - bootloader
          - shellprocess@grub_crypt
          - grubcfg-fix
          - postcfg
          - btrfs-fix
          - umount
    - show:
          - finished

branding: xivastudio
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: true
quit-at-end: false
