---
units:
    - name: bluetooth
      action: enable
      mandatory: false
    - name: cronie
      action: enable
      mandatory: false
    - name: ModemManager
      action: enable
      mandatory: false
    - name: NetworkManager
      action: enable
      mandatory: false
    - name: cups
      action: enable
      mandatory: false
    - name: fstrim.timer
      action: enable
      mandatory: false
    - name: pkgfile-update.timer
      action: enable
      mandatory: false
    - name: vboxservice
      action: enable
      mandatory: false
    - name: ufw
      action: enable
      mandatory: false
    - name: nmb
      action: enable
      mandatory: false
    - name: smb
      action: enable
      mandatory: false
    - name: dnsmasq
      action: enable
      mandatory: false
    - name: cups-browsed
      action: enable
      mandatory: false
    - name: sddm
      action: enable
      mandatory: false
    - name: graphical.target
      action: set-default
      mandatory: false
    - name: pacman-init
      action: mask
      mandatory: false
