# BigLinux welcomeq configuration.
# SPDX-License-Identifier: CC0-1.0
---
# Load the BigLinux QML shipped by this branding component.
qmlSearch: branding
qmlFilename: welcomeq

showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false
showDonateUrl: false

requirements:
    internetCheckUrl: https://google.com
    requiredStorage: 4
    requiredRam: 0.5
    check:
        - storage
        - ram
        - power
        - internet
        - root
    required:
        - storage
        - ram
        - root

geoip:
    style: xml
    url: https://geoip.kde.org/v1/ubiquity
    selector: CountryCode
