#!/bin/sh
set -e
package_name=biglinux-livecd
mkdir -p "/usr/share/dpkgdivert/biglinux-livecd"
case "$1" in
  install)
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/biglinux-livecd/usrshareinitramfs-toolsscriptscasper-bottom33enable_apport_crashes" --rename "/usr/share/initramfs-tools/scripts/casper-bottom/33enable_apport_crashes"
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/biglinux-livecd/usrshareinitramfs-toolsscriptscasper-bottom53disable_unattended_upgrades" --rename "/usr/share/initramfs-tools/scripts/casper-bottom/53disable_unattended_upgrades"
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/biglinux-livecd/usrshareinitramfs-toolsscriptscasper-bottom31disable_update_notifier" --rename "/usr/share/initramfs-tools/scripts/casper-bottom/31disable_update_notifier"
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/biglinux-livecd/etccasper.conf" --rename "/etc/casper.conf"
    ;;
  upgrade)
if [ "$(dpkg-divert --list "/usr/share/initramfs-tools/scripts/casper-bottom/33enable_apport_crashes")" = "" ]
then
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/biglinux-livecd/usrshareinitramfs-toolsscriptscasper-bottom33enable_apport_crashes" --rename "/usr/share/initramfs-tools/scripts/casper-bottom/33enable_apport_crashes"
fi
if [ "$(dpkg-divert --list "/usr/share/initramfs-tools/scripts/casper-bottom/53disable_unattended_upgrades")" = "" ]
then
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/biglinux-livecd/usrshareinitramfs-toolsscriptscasper-bottom53disable_unattended_upgrades" --rename "/usr/share/initramfs-tools/scripts/casper-bottom/53disable_unattended_upgrades"
fi
if [ "$(dpkg-divert --list "/usr/share/initramfs-tools/scripts/casper-bottom/31disable_update_notifier")" = "" ]
then
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/biglinux-livecd/usrshareinitramfs-toolsscriptscasper-bottom31disable_update_notifier" --rename "/usr/share/initramfs-tools/scripts/casper-bottom/31disable_update_notifier"
fi
if [ "$(dpkg-divert --list "/etc/casper.conf")" = "" ]
then
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/biglinux-livecd/etccasper.conf" --rename "/etc/casper.conf"
fi
;;
esac
exit 0
