#!/bin/bash

if [ "$(file -i /usr/bin/calamares | grep shellscript)" = "" ]; then
    # calamares
    mv -f /usr/bin/calamares /usr/bin/calamares-manjaro
    ln -s /usr/bin/calamares-biglinux /usr/bin/calamares

    # calamares_polkit
    mv -f /usr/bin/calamares_polkit /usr/bin/calamares-manjaro_polkit
    ln -s /usr/bin/calamares-biglinux_polkit /usr/bin/calamares_polkit
fi

rm -f /usr/share/applications/calamares.desktop
